openapi: '3.0.0'
info:
  title: reader contract
  version: '1.0.0'
paths:
  /api/v1/read:
    post:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
