openapi: '3.0.0'
info:
  title: vector contract
  version: '1.0.0'
paths:
  /search/vector:
    post:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
